Change hash generation logic
LT-Students/DigitalOffice-UserService pull request #12
Opened 2020-10-11 14:37 UTC by lalagvana

2020-10-11 15:09 UTC, djino97 commented on test/UserService.Mappers.UnitTests/UserCredentialsMapperTests.cs
> +                    Encoding.UTF8.GetBytes(result.Salt + userRequest.Login + userRequest.Password + SALT3)));
use interpolation, uses slightly less memory

2020-10-11 15:43 UTC, lalagvana commented on src/UserService.Mappers/UserCredentialsMapper.cs
> +        internal static string SALT3 = "LT.DigitalOffice.SALT3";
![image](https://user-images.githubusercontent.com/59228285/95683056-9634d200-0bf1-11eb-968c-b2f54d229b4f.png)

2020-10-12 17:24 UTC, djino97 commented on src/UserService/UserService.csproj
> +    <PackageReference Include="MassTransit.RabbitMQ" Version="7.0.4" />
remove

2020-10-12 17:24 UTC, djino97 commented on src/UserService/UserService.csproj
> +    <PackageReference Include="FluentValidation" Version="9.2.2" />
remove

2020-10-12 17:24 UTC, djino97 commented on test/UserService.Business.UnitTests/UserService.Business.UnitTests.csproj
> +    <PackageReference Include="FluentValidation" Version="9.2.2" />
remove

2020-10-12 17:24 UTC, djino97 commented on src/UserService.Mappers/UserCredentialsMapper.cs
> +        internal static string SALT3 = "LT.DigitalOffice.SALT3";
Maybe move it to the static class and with static method generation password hash?

2020-10-12 17:27 UTC, DarkFelas requested changes

2020-10-12 17:27 UTC, DarkFelas commented on src/UserService.Business/DisableUserByIdCommand.cs
> +        private bool GetResultCheckingUserRights()
const int rightId = 1;

return accessValidator.IsAdmin() || accessValidator.HasRights(rightId);

2020-10-12 17:27 UTC, DarkFelas commented on src/UserService.Business/DisableUserByIdCommand.cs
> +            var isAccess = GetResultCheckingUserRights();
remove isAccess variable, move GetResultCheckingUserRights() inside IF

2020-10-12 17:27 UTC, DarkFelas commented on src/UserService.Business/DisableUserByIdCommand.cs
>                  throw new Exception("Not enough rights.");
Kernel ForbiddenException

2020-10-12 17:27 UTC, DarkFelas commented on src/UserService.Mappers/UserCredentialsMapper.cs
>                  PasswordHash = Encoding.UTF8.GetString(new SHA512Managed().ComputeHash(
Create some helper for this method

2020-10-12 17:27 UTC, DarkFelas commented on src/UserService.Mappers/UserCredentialsMapper.cs
>                  throw new ArgumentNullException(nameof(request));
BadRequestException

2020-10-12 17:27 UTC, DarkFelas commented on test/UserService.Data.UnitTests/UserCredentialsRepositoryTests.cs
> +        internal const string SALT3 = "LT.DigitalOffice.SALT3";
Remove this one from here, use 
https://docs.microsoft.com/ru-ru/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute?view=netcore-3.1

2020-10-13 14:46 UTC, djino97 commented on src/UserService.Mappers/UserCredentialsMapper.cs
> +        internal static string SALT3 = "LT.DigitalOffice.SALT3";
And this field should be const string

2020-10-16 17:14 UTC, DarkFelas approved these changes

2020-10-16 19:45 UTC, djino97 commented on test/UserService.Business.UnitTests/DisablingUserByIdCommandTests.cs
> -            repositoryMock.Verify(repository => repository.EditUser(It.IsAny<DbUser>()), Times.Once);
Why removed?

2020-10-16 19:45 UTC, djino97 commented on src/UserService.Models.Dto/UserPassword.cs
> +[assembly: InternalsVisibleTo("LT.DigitalOffice.UserService.Mappers")]
Why separated? Maybe made collapse 
![image](https://user-images.githubusercontent.com/38541098/96301804-65dda100-1000-11eb-88ab-d1105cd84986.png)

2020-10-16 19:45 UTC, djino97 commented on src/UserService.Business/DisableUserByIdCommand.cs
> +            const int rightId = 1;
Maybe move this in field of class?

2020-10-17 10:14 UTC, lalagvana commented on src/UserService.Business/DisableUserByIdCommand.cs
> +            const int rightId = 1;
I'm not sure it's really needed

2020-10-17 10:22 UTC, djino97 commented on src/UserService.Business/DisableUserByIdCommand.cs
>          public void Execute(Guid userId, Guid requestingUserId)
And requestingUserId is not needed here

2020-10-17 10:49 UTC, djino97 approved these changes

2020-10-17 10:57 UTC, merged