Change password endpoint
LT-Students/DigitalOffice-UserService pull request #13
Opened 2020-10-11 15:42 UTC by lalagvana

2020-10-12 17:18 UTC, DarkFelas requested changes

2020-10-12 17:18 UTC, DarkFelas commented on src/UserService.Data/UserCredentialsRepository.cs
> +                throw new Exception("User credentials with this user login not found.");
Kernel NotFoundException

2020-10-12 17:18 UTC, DarkFelas commented on src/UserService.Data/UserCredentialsRepository.cs
> +            userCredentials.PasswordHash = Encoding.UTF8.GetString(new SHA512Managed().ComputeHash(
What about new hash generation logic?

2020-10-12 17:18 UTC, DarkFelas commented on test/UserService.Data.UnitTests/UserCredentialsRepositoryTests.cs
> +            Assert.Throws<Exception>(() => repository.ChangePassword("login12345", "newPassword"));
NotFoundException

2020-10-12 17:18 UTC, DarkFelas commented on test/UserService.Business.UnitTests/ChangePasswordCommandTests.cs
> +    {
Tests???

2020-11-03 11:19 UTC, KostinP approved these changes

2020-11-03 13:17 UTC, djino97 commented on src/UserService.Business/ChangePasswordCommand.cs
> +            repository.ChangePassword(request.Login, request.NewPassword);
And probably here must need check generatedId from cache(created in ForgotUserPassword)

2020-12-08 19:14 UTC, DarkFelas approved these changes

2020-12-09 18:19 UTC, merged