GetUsersByIds logic
LT-Students/DigitalOffice-UserService pull request #15
Opened 2020-10-15 13:46 UTC by lalagvana

2020-10-16 09:32 UTC, DarkFelas requested changes

2020-10-16 09:32 UTC, DarkFelas commented on src/UserService.Business/GetUsersByIdsCommand.cs
> +                users.Add(mapper.Map(repository.GetUserInfoById(userId)));
not rly good, this logic will create a lot of independent queries to our DB, plz create new method in user repository to get IEnumerable<DbUser> in single query

2020-10-16 09:32 UTC, DarkFelas commented on src/UserService.Data/UserRepository.cs
> +               throw new NotFoundException("User with this id was not found.");
Add ID value to message

2020-10-16 09:32 UTC, DarkFelas commented on src/UserService.Data/UserRepository.cs
> +                throw new NotFoundException("User was not found.");
Add ID value to message

2020-10-16 09:32 UTC, DarkFelas commented on src/UserService.Data/UserRepository.cs
> +                throw new NotFoundException("User credentials not found.");
Add email value to message

2020-10-16 17:21 UTC, DarkFelas approved these changes

2020-10-29 00:03 UTC, djino97 commented on test/UserService.Business.UnitTests/GetUsersByIdsCommandTests.cs
> +        [SetUp]
OneTimeSetUp

2020-10-29 00:03 UTC, djino97 commented on test/UserService.Data.UnitTests/UserRepositoryTests.cs
> +            Assert.That(result, Is.EquivalentTo(new[] { firstUser }));
AreEqual?

2020-10-30 12:59 UTC, djino97 approved these changes

2020-10-30 16:36 UTC, merged