Feature add email resender
LT-Students/DigitalOffice-UserService pull request #46
Opened 2021-04-18 19:15 UTC by 24eeeee

2021-04-18 19:33 UTC, KostinP requested changes
Thank you for the courage in posting! This makes it easier to comment on the code.

We are also waiting:
- Update CommandTests
- Add EmailResenderTests

2021-04-18 19:33 UTC, KostinP commented on src/UserService.Business/Helpers/Email/EmailResender.cs
> +                            _logger.LogWarning($"Can not send email. Email remain in resend queue.");
What email were you trying to forward?

2021-04-18 19:33 UTC, KostinP commented on src/UserService.Business/Helpers/Email/EmailResender.cs
> +                        _logger.LogError(exc, $"Errors while sending email. Email remain in resend queue.");
What is the error message?

2021-04-18 19:33 UTC, KostinP commented on src/UserService.Business/Helpers/Email/EmailResender.cs
> +        private static readonly ILogger<EmailResender> _logger;
Add constructor (.NET will inject dependencies)

2021-04-18 19:33 UTC, KostinP commented on src/UserService/Startup.cs
> +            Task.Run(() => EmailResender.Start(_emailEngineConfig.ResendInterval));
Add read from enviroment

2021-04-18 19:33 UTC, KostinP commented on src/UserService/Startup.cs
> +        private readonly EmailEngineConfig _emailEngineConfig;
Why is not local variable?

2021-04-19 09:15 UTC, TIove commented on src/UserService/appsettings.json
> +    "ResendInterval": 60
It is better to use postfix "InMinutes" or "InSeconds", because now it is unclear

2021-04-22 13:16 UTC, KostinP approved these changes

2021-04-22 13:27 UTC, TIove approved these changes

2021-04-25 13:15 UTC, MariyaSin commented on src/UserService.Business/Commands/User/CreateUserCommand.cs
> +
remove empty line

2021-04-25 13:15 UTC, MariyaSin approved these changes

2021-04-27 08:04 UTC, BelehovEgor approved these changes

2021-04-27 14:15 UTC, merged